name: Build & Deploy Godot Game

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gamon-games  # alle commands draaien in deze folder

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download Godot
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_linux.x86_64.zip
          unzip Godot_v4.2.2-stable_linux.x86_64.zip
          mv Godot_v4.2.2-stable_linux.x86_64 ../godot
          chmod +x ../godot

      - name: Install export templates
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/4.2.2.stable
          unzip Godot_v4.2.2-stable_export_templates.tpz -d templates
          mv templates/templates/* ~/.local/share/godot/export_templates/4.2.2.stable/

      - name: Create build folder
        run: mkdir -p build

      - name: Build Windows
        run: ../godot --headless --export-release "Windows Desktop" build/game.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: godot-builds
          path: gamon-games/build/
